/**
 * What `dev:web` boots from: whole snapshots, checked in, with no Rust process
 * anywhere behind them.
 *
 * Every file in `./fixtures/` is **generated by the model crate from a recorded
 * GitHub answer** — `crates/model/src/bindings.rs` derives them and fails the
 * Rust build if a checked-in one has stopped matching. That is what keeps them
 * from becoming a second, drifting account of what the model does: a fixture
 * here is the model's own output, or it is fiction.
 *
 * The set is chosen for the states a graph is hard to get into on purpose — an
 * unclassified child, a closed ticket whose blocker is still open, two spec
 * children, a spec child that would otherwise be takeable, a map with nothing
 * on it, a closed map, and **each of the four conditions a failed poll can be
 * in**. The last of those is why there are four failure fixtures and not one: a
 * browser has no way to revoke a token or delete a repository, and two of the
 * four stop the poller and print a remedy while the other two keep trying.
 *
 * `platform-bound-macos` and `platform-bound-windows` are the same recorded
 * answer derived twice, and they are here because the machine an operator is
 * sitting at is not something a browser can be talked into being. Between them
 * they hold the two readings of an empty frontier: one is a map this machine
 * can start work on, the other is the same map with every startable ticket on
 * it bound to a machine this is not — every row still listed, still counted,
 * and none of them offered.
 *
 * `while-you-were-away` is there for the same reason: reaching the cold-start
 * row needs a cached graph from a session that ended, and a `dev:web` tab has
 * no previous session to have ended. It and `ledger-sweep` are the only two
 * ledgers on disk that are not empty, which is what makes a real zero and
 * *first open* distinguishable on screen.
 *
 * `ledger-sweep` is the second of those and divides the ledger with the first
 * rather than duplicating it. `while-you-were-away` is what a real morning
 * looks like, and is where the *precedence* between clause kinds is legible.
 * `ledger-sweep` is deliberately not realistic: it is one map moved in every
 * way the change vocabulary has a word for, so the *set* of clause kinds is
 * something the screen has been asked about rather than a vocabulary only the
 * model crate's unit tests have ever seen. Sixteen clauses in one entry is not
 * a morning's polling, and an entry that looked like one would reach four of
 * the sixteen words — which is why merging the two would lose both readings.
 *
 * The three fog fixtures are there because the fog is the one region whose
 * *absence* is the fact: a browser has no way to edit a map document, and
 * *nobody surveyed*, *surveyed and found nothing* and *surveyed and wrote four
 * lines* are three states that must be tellable apart on screen and not only in
 * the type.
 *
 * `spec-ready` is the phase ladder's bottom rung, and it is here because the
 * ladder is a closed set the screen has to be able to spell all of: every
 * ticket closed and no spec child at all. Reaching it in a browser would mean
 * closing every ticket on a map and composing nothing, which is a sequence of
 * clicks against a real GitHub rather than a state a tab can be put into — and
 * without it the word `PHASE_NAMES` keeps for that rung is a string no rendered
 * state ever asks about. It sits one child away from `spec-composed`, so *ready
 * to compose* and *composed* are two readings on screen rather than one word an
 * operator has to take on trust.
 *
 * `out-of-scope` is there for both halves of that reason at once. A browser
 * cannot edit a map document, and *closed as done* and *closed because it was
 * cut* are the same `CLOSED` in the API — the difference lives in a section of
 * the map's body, so there is no sequence of clicks that reaches this state. It
 * carries a cut ticket beside a plainly resolved one, so the reason on screen
 * and the resolved count that no longer includes it are both visible rather
 * than asserted, and an out-of-scope line pointing at a still-open ticket that
 * goes on being takeable with nothing said about it.
 */

import type { Snapshot } from "./model.generated";

/* `with { type: "json" }` on every one of these. Vite does not need it, but
   the conformance suite loads this module in plain Node ESM to learn the
   fixture names, and Node refuses a JSON specifier without the attribute — so
   without it the suite has no way to reach the list except by keeping a second
   copy of it. */
import authFailed from "./fixtures/auth-failed.json" with { type: "json" };
import awkwardMap from "./fixtures/awkward-map.json" with { type: "json" };
import emptyMap from "./fixtures/empty-map.json" with { type: "json" };
import fogCharted from "./fixtures/fog-charted.json" with { type: "json" };
import fogEmpty from "./fixtures/fog-empty.json" with { type: "json" };
import fogUnsurveyed from "./fixtures/fog-unsurveyed.json" with { type: "json" };
import ledgerSweep from "./fixtures/ledger-sweep.json" with { type: "json" };
import mapClosed from "./fixtures/map-closed.json" with { type: "json" };
import mapGone from "./fixtures/map-gone.json" with { type: "json" };
import noMapOpen from "./fixtures/no-map-open.json" with { type: "json" };
import outOfScope from "./fixtures/out-of-scope.json" with { type: "json" };
import platformBoundMacos from "./fixtures/platform-bound-macos.json" with { type: "json" };
import platformBoundWindows from "./fixtures/platform-bound-windows.json" with { type: "json" };
import rateLimited from "./fixtures/rate-limited.json" with { type: "json" };
import specComposed from "./fixtures/spec-composed.json" with { type: "json" };
import specReady from "./fixtures/spec-ready.json" with { type: "json" };
import twoMapsOneOpen from "./fixtures/two-maps-one-open.json" with { type: "json" };
import unreachable from "./fixtures/unreachable.json" with { type: "json" };
import whileYouWereAway from "./fixtures/while-you-were-away.json" with { type: "json" };

/*
 * `as unknown as Snapshot`, and for the same reason `maps.ts` does it:
 * TypeScript widens every string in an imported JSON module to `string`, so a
 * direct annotation would reject `"takeable"` for not being the union it
 * literally is. The cast is not where the honesty comes from — the Rust test
 * that regenerates these files is, and it compares them byte for byte against
 * what the model produces.
 */
const AS_GENERATED = (json: unknown) => json as Snapshot;

export const FIXTURES = {
  "auth-failed": AS_GENERATED(authFailed),
  "awkward-map": AS_GENERATED(awkwardMap),
  "empty-map": AS_GENERATED(emptyMap),
  "fog-charted": AS_GENERATED(fogCharted),
  "fog-empty": AS_GENERATED(fogEmpty),
  "fog-unsurveyed": AS_GENERATED(fogUnsurveyed),
  "ledger-sweep": AS_GENERATED(ledgerSweep),
  "map-closed": AS_GENERATED(mapClosed),
  "map-gone": AS_GENERATED(mapGone),
  "no-map-open": AS_GENERATED(noMapOpen),
  "out-of-scope": AS_GENERATED(outOfScope),
  "platform-bound-macos": AS_GENERATED(platformBoundMacos),
  "platform-bound-windows": AS_GENERATED(platformBoundWindows),
  "rate-limited": AS_GENERATED(rateLimited),
  "spec-composed": AS_GENERATED(specComposed),
  "spec-ready": AS_GENERATED(specReady),
  "two-maps-one-open": AS_GENERATED(twoMapsOneOpen),
  unreachable: AS_GENERATED(unreachable),
  "while-you-were-away": AS_GENERATED(whileYouWereAway),
} as const;

export type FixtureName = keyof typeof FIXTURES;

export const FIXTURE_NAMES = Object.keys(FIXTURES) as FixtureName[];

/**
 * The one `dev:web` opens on. The awkward map, deliberately: it is the fixture
 * where every rule this slice added is visible at once, so the default view is
 * the one that would show a rule having broken.
 */
export const DEFAULT_FIXTURE: FixtureName = "awkward-map";

/** A copy each time, so a caller editing one cannot edit the fixture itself. */
export function fixtureNamed(name: FixtureName): Snapshot {
  return structuredClone(FIXTURES[name]);
}

/**
 * Which fixture a `dev:web` URL asked for.
 *
 * `?map=` rather than `?fixture=`, because `environment.ts` already spells this
 * `?env=`: the parameter names the thing being stood in for and the value names
 * the state. One convention, so a second one does not have to be learned.
 *
 * An unknown name falls back to the default rather than throwing: a typo in a
 * query string is not worth a blank window.
 */
export const FIXTURE_PARAMETER = "map";

export function requestedFixture(search?: string): FixtureName {
  const from =
    search ?? (typeof window === "undefined" ? "" : window.location.search);
  const asked = new URLSearchParams(from).get(FIXTURE_PARAMETER);
  return isFixtureName(asked) ? asked : DEFAULT_FIXTURE;
}

export function isFixtureName(name: string | null): name is FixtureName {
  return name !== null && name in FIXTURES;
}
