/**
 * What `dev:web` boots from: whole snapshots, checked in, with no Rust process
 * anywhere behind them.
 *
 * Every file in `./fixtures/` is **generated by the model crate from a recorded
 * GitHub answer** — `crates/model/src/bindings.rs` derives them and fails the
 * Rust build if a checked-in one has stopped matching. That is what keeps them
 * from becoming a second, drifting account of what the model does: a fixture
 * here is the model's own output, or it is fiction.
 *
 * The set is chosen for the states a graph is hard to get into on purpose — an
 * unclassified child, a closed ticket whose blocker is still open, two spec
 * children, a spec child that would otherwise be takeable, a map with nothing
 * on it, a closed map, and a poll that failed. Those are the ones worth being
 * able to look at without waiting for GitHub to produce one.
 */

import type { Snapshot } from "./model.generated";

import awkwardMap from "./fixtures/awkward-map.json";
import emptyMap from "./fixtures/empty-map.json";
import mapClosed from "./fixtures/map-closed.json";
import noMapOpen from "./fixtures/no-map-open.json";
import specComposed from "./fixtures/spec-composed.json";
import twoMapsOneOpen from "./fixtures/two-maps-one-open.json";
import unreachable from "./fixtures/unreachable.json";

/*
 * `as unknown as Snapshot`, and for the same reason `maps.ts` does it:
 * TypeScript widens every string in an imported JSON module to `string`, so a
 * direct annotation would reject `"takeable"` for not being the union it
 * literally is. The cast is not where the honesty comes from — the Rust test
 * that regenerates these files is, and it compares them byte for byte against
 * what the model produces.
 */
const AS_GENERATED = (json: unknown) => json as Snapshot;

export const FIXTURES = {
  "awkward-map": AS_GENERATED(awkwardMap),
  "empty-map": AS_GENERATED(emptyMap),
  "map-closed": AS_GENERATED(mapClosed),
  "no-map-open": AS_GENERATED(noMapOpen),
  "spec-composed": AS_GENERATED(specComposed),
  "two-maps-one-open": AS_GENERATED(twoMapsOneOpen),
  unreachable: AS_GENERATED(unreachable),
} as const;

export type FixtureName = keyof typeof FIXTURES;

export const FIXTURE_NAMES = Object.keys(FIXTURES) as FixtureName[];

/**
 * The one `dev:web` opens on. The awkward map, deliberately: it is the fixture
 * where every rule this slice added is visible at once, so the default view is
 * the one that would show a rule having broken.
 */
export const DEFAULT_FIXTURE: FixtureName = "awkward-map";

/** A copy each time, so a caller editing one cannot edit the fixture itself. */
export function fixtureNamed(name: FixtureName): Snapshot {
  return structuredClone(FIXTURES[name]);
}

/**
 * Which fixture a `dev:web` URL asked for.
 *
 * `?map=` rather than `?fixture=`, because `environment.ts` already spells this
 * `?env=`: the parameter names the thing being stood in for and the value names
 * the state. One convention, so a second one does not have to be learned.
 *
 * An unknown name falls back to the default rather than throwing: a typo in a
 * query string is not worth a blank window.
 */
export const FIXTURE_PARAMETER = "map";

export function requestedFixture(search?: string): FixtureName {
  const from =
    search ?? (typeof window === "undefined" ? "" : window.location.search);
  const asked = new URLSearchParams(from).get(FIXTURE_PARAMETER);
  return isFixtureName(asked) ? asked : DEFAULT_FIXTURE;
}

export function isFixtureName(name: string | null): name is FixtureName {
  return name !== null && name in FIXTURES;
}
