// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three categories a child of a map can fall into.
 *
 * The third row is the one that is easy to leave out and expensive to have
 * left out: without it every child is either a ticket or a spec, and a child
 * that is neither becomes whichever of the two the code happened to default
 * to. Both defaults are wrong in a way an operator cannot see.
 */
export type ChildKind = { "kind": "ticket", "type": TicketType } | { "kind": "spec" } | { "kind": "unclassified" };

/**
 * Three counts, and the ladder is built from them.
 *
 * *Resolved* is not a fourth field: it is `tickets - open`, and a fourth
 * number is a fourth thing that can disagree with the other three.
 */
export type Counts = { 
/**
 * Ticket-classified children. The spec is not one, and neither is an
 * unclassified child — counting either would put a number on screen the
 * frontier can never work through.
 */
tickets: number, 
/**
 * Ticket-classified children still open.
 */
open: number, 
/**
 * Children labelled `wayfinder:spec`. Plural on purpose: more than one is
 * a state the map can be in and a thing an operator has to be able to see,
 * not an invariant this file gets to assume.
 */
specs: number, };

/**
 * One map, derived.
 */
export type Map = { number: number, title: string, 
/**
 * The map's own state, carried because it is the top rung of the ladder
 * and no ticket can put the map on it.
 */
closed: boolean, phase: Phase, counts: Counts, 
/**
 * **Sub-issue order.** The operator dragged these into this order in
 * GitHub's own UI, so it is their order and this app never re-sorts it —
 * not by number, and emphatically not by a ranking of its own. A frontier
 * picked by a ranking is a frontier the graph on screen cannot justify.
 */
nodes: Array<Node>, 
/**
 * The designated frontier: the number of the first node in map order that
 * [`Node::is_takeable`] admits. `None` when nothing on this map can be
 * started, which is a state with its own reading and not a zero.
 */
frontier: number | null, };

/**
 * The derived model for one tick, whole.
 *
 * `PartialEq` is the point of this type: **changed means `new.model !=
 * old.model`**, structural equality over the whole of it. No hash, no
 * fingerprint and no chosen field set — a shortlist is a field added later,
 * forgotten, and the graph going quietly wrong with nothing on screen to say
 * so.
 */
export type Model = { 
/**
 * `None` is *no map open* — an absence, never an empty map. The chrome
 * exists before it holds anything, and a map with no tickets in it is a
 * different fact again (see [`Phase::Unstarted`]).
 */
map: Map | null, };

/**
 * One child of the map, derived.
 *
 * What is *not* here is as deliberate as what is: no blocker count, no
 * assignee list, no `updatedAt`. The first two are the inputs to a decision
 * already made, and re-exporting them is how a second frontier resolver gets
 * written by accident; the third is a timestamp, and this model reads none.
 */
export type Node = { number: number, title: string, url: string, kind: ChildKind, state: NodeState, 
/**
 * What this one waits on, by number, in the order the answer listed them.
 * The graph's edges, and the only adjacency that crosses.
 *
 * Adjacency is not one of the inputs above and cannot be turned back into
 * one. A node's state is decided from GitHub's count of the blockers still
 * in the way, which stays behind; these numbers are *every* blocker the
 * answer named, finished ones included, and one of them may be an issue
 * that is not a child of this map and so has no state on this side at all.
 * A second state resolver written from these would be wrong in both
 * directions, which is the reason the count it would need is still absent.
 *
 * It crosses as edges rather than as a count of what each node opens up,
 * because a rank is *how far along* and there is no way to compute one
 * from a number.
 */
waitsOn: Array<number>, };

/**
 * The four states, and there is no fifth.
 *
 * The precedence is strict and top-down — **closed beats blocked beats
 * claimed** — which is why a closed ticket with an open blocker reads as
 * resolved rather than as blocked. Work that is finished is finished; that
 * something still points at it is a fact about the blocker.
 */
export type NodeState = "resolved" | "blocked" | "claimed" | "takeable";

/**
 * Where the map is in the loop, derived rather than stored.
 *
 * Stored, it could disagree with the tickets. Derived, it cannot — which is
 * the whole reason this is a function of the counts and not a field somebody
 * maintains.
 */
export type Phase = "done" | "unstarted" | "wayfinding" | "specced" | "specReady";

/**
 * How this snapshot came to exist, and when. Age is always renderable because
 * provenance is part of the snapshot rather than a sibling of it.
 *
 * **No `PartialEq`, on purpose.** Change detection is the model's business and
 * only the model's; a `Provenance` that could be compared is a `Provenance`
 * that ends up inside somebody's equality check, and the field most likely to
 * be reached for there is a timestamp. The absence of the trait is what makes
 * that a compile error rather than a code-review habit.
 */
export type Provenance = { source: Source, outcome: ReadOutcome, 
/**
 * RFC 3339. Carried as text so this crate needs no clock and no time
 * dependency — the caller that has a clock stamps it.
 */
fetchedAt: string | null, };

export type ReadOutcome = { "kind": "ok" } | { "kind": "failed", "detail": string } | { "kind": "notAttempted" };

/**
 * Everything the WebView is given for one tick.
 *
 * One type, and the derivation is already done inside it. The same artifact is
 * [`crate::derive`]'s output and the frontend's input, which is what makes this
 * one seam rather than two — and it lands a cheap constraint that pays for
 * itself: **a snapshot must be constructible from a JSON file as easily as
 * from GitHub**, which is what lets `dev:web` boot the whole frontend with no
 * Rust, no GitHub and no PTY behind it.
 *
 * **Provenance is fused into this value rather than streamed beside it.** Two
 * streams would let a fresh model paint against a stale stamp for a frame —
 * absence disguised as presence, which is the one failure this whole design is
 * arranged to make unrepresentable. Atomic replacement is what makes it so.
 *
 * There is deliberately no `PartialEq` here. Comparing two snapshots would
 * compare their provenance, and provenance moves on every tick — so a
 * snapshot-level comparison answers *did we look again* when the question is
 * always *did anything change*. [`Snapshot::changed_from`] is the only
 * comparison there is, and it is the model's.
 */
export type Snapshot = { schemaVersion: number, model: Model, provenance: Provenance, };

export type Source = "github" | "cache" | "fixture" | "none";

/**
 * The kinds of work a ticket can be, as `/to-issues` labels them.
 */
export type TicketType = "research" | "prototype" | "grilling" | "task";
