import { hasRustBehindIt } from "../snapshot/snapshot";
import type { RunReadout } from "./runs";

/**
 * What `dev:web` boots a rack of runs from: hand-written readouts, checked in,
 * with no PTY and no Rust process anywhere behind them.
 *
 * They exist because the states worth looking at are the ones a browser cannot
 * be talked into. Spec #28 names it exactly — *you cannot conjure a wedged AFK
 * run to check its still-state* — and neither can a Tauri window on demand: a
 * wedged reading wants five minutes of a research run saying nothing, and an
 * `awaitingOperator` one wants a CLI that stopped on a trust prompt, which is a
 * machine state rather than a click.
 *
 * **They are not the snapshot fixtures, and the difference is their whole
 * weakness.** `src/snapshot/fixtures.ts` holds files *generated by the model
 * crate*, and the Rust build fails if a checked-in one has stopped matching —
 * so a snapshot fixture is the model's own output or it is nothing. A run
 * readout is not part of `Snapshot`, no generator emits one, and the only thing
 * standing between this file and fiction is the `RunReadout` annotation below
 * plus the two tests that pin the wire shape from either side. Adding a key in
 * Rust will not fail this file; renaming one will fail `tsc`, and that is the
 * line being relied on.
 *
 * Nothing here ever presents itself as a live read. The seeding below is on the
 * no-Rust branch only, for the same reason no snapshot fixture is stamped
 * `github`: a browser quietly showing fiction as an observation is the one
 * failure the provenance rules exist to prevent.
 */

/**
 * Everything a readout carries that these fixtures are not making a point
 * about. Typed as `RunReadout` so a key added on the Rust side and mirrored
 * into the interface fails the build here rather than being silently absent
 * from every fixture.
 */
const ORDINARY: RunReadout = {
  run: 0,
  held: 0,
  dropped: 0,
  through: 0,
  end: 0,
  truncated: false,
  desynced: false,
  over: false,
  code: null,
  monitored: false,
  ending: "live",
  ticket: null,
  folder: null,
  silence: { kind: "nothing" },
  signal: null,
};

function a(readout: Partial<RunReadout> & Pick<RunReadout, "run">): RunReadout {
  return { ...ORDINARY, ...readout };
}

/** An hour of a person reading a diff, which is the most ordinary thing there is. */
const QUIET_HOUR = a({
  run: 1,
  ticket: 50,
  folder: "/work/perseverance",
  held: 262_144,
  through: 262_144,
  end: 262_144,
  monitored: true,
  silence: { kind: "quiet", silentForMs: 62 * 60_000 },
  signal: "busy",
});

/** A CLI that never opened its session, because its own trust prompt is up. */
const AWAITING_OPERATOR = a({
  run: 2,
  ticket: 51,
  folder: "/work/perseverance",
  monitored: true,
  silence: { kind: "wedged", why: "awaitingOperator", silentForMs: 12_000 },
});

/**
 * The one this file exists for: an unattended run, silent past the fallback,
 * with nobody in front of it and no signal ever observed.
 */
const UNWATCHED = a({
  run: 3,
  ticket: 52,
  folder: "/work/perseverance",
  held: 8_192,
  through: 8_192,
  end: 8_192,
  monitored: true,
  silence: { kind: "wedged", why: "silent", silentForMs: 5 * 60_000 + 4_000 },
});

/** A closed ticket over a child that may still be printing. Never quiet, ever. */
const SPENT = a({
  run: 4,
  ticket: 47,
  folder: "/work/perseverance",
  held: 131_072,
  through: 131_072,
  end: 131_072,
  monitored: true,
  ending: "spent",
  silence: { kind: "spent" },
  signal: "ready",
});

/** A child that stopped, where the ending is the reading and the silence is not. */
const ENDED = a({
  run: 5,
  ticket: 44,
  folder: "/work/perseverance",
  held: 65_536,
  through: 65_536,
  end: 65_536,
  over: true,
  code: 130,
  monitored: true,
  ending: "exited",
});

/** A run a watch has seen go idle, so the third signal is a thing on screen too. */
const IDLING = a({
  run: 6,
  ticket: 53,
  folder: "/work/other",
  held: 4_096,
  through: 4_096,
  end: 4_096,
  silence: { kind: "quiet", silentForMs: 90_000 },
  signal: "idle",
});

/**
 * The sets, each named for the reading it is there to put on screen.
 *
 * `none` is the default and is empty, so that a `dev:web` tab opened without
 * asking for runs is the tab this app has always opened: nothing bound, and
 * *Nothing is running here yet.* still a state somebody can look at.
 *
 * `the-rack` is every reading at once and every signal at once, which is the
 * only place the four silences can be compared rather than remembered.
 */
export const RUN_FIXTURES = {
  none: [],
  quiet: [QUIET_HOUR],
  "awaiting-operator": [AWAITING_OPERATOR],
  unwatched: [UNWATCHED],
  spent: [SPENT],
  ended: [ENDED],
  "the-rack": [
    a({ ...AWAITING_OPERATOR, monitored: true }),
    a({ ...QUIET_HOUR, monitored: false }),
    a({ ...UNWATCHED, monitored: false }),
    a({ ...SPENT, monitored: false }),
    a({ ...ENDED, monitored: false }),
    IDLING,
  ],
} satisfies Record<string, RunReadout[]>;

export type RunFixtureName = keyof typeof RUN_FIXTURES;

export const RUN_FIXTURE_NAMES = Object.keys(RUN_FIXTURES) as RunFixtureName[];

export const DEFAULT_RUN_FIXTURE: RunFixtureName = "none";

/** A copy each time, so a caller editing one cannot edit the fixture itself. */
export function runFixtureNamed(name: RunFixtureName): RunReadout[] {
  return structuredClone(RUN_FIXTURES[name]) as RunReadout[];
}

/**
 * Which set of runs a `dev:web` URL asked for.
 *
 * `?runs=` beside `?map=` and `?env=`, spelled once here: the parameter names
 * the thing being stood in for and the value names the state. An unknown name
 * falls back to the default rather than throwing, for the same reason a typo in
 * `?map=` does not blank the window.
 */
export const RUNS_PARAMETER = "runs";

export function requestedRunFixture(search?: string): RunFixtureName {
  const from = search ?? (typeof window === "undefined" ? "" : window.location.search);
  const asked = new URLSearchParams(from).get(RUNS_PARAMETER);
  return isRunFixtureName(asked) ? asked : DEFAULT_RUN_FIXTURE;
}

export function isRunFixtureName(name: string | null): name is RunFixtureName {
  return name !== null && name in RUN_FIXTURES;
}

/**
 * Which of a fixture set's runs the pane opens on, and `null` whenever there is
 * a harness behind the window.
 *
 * Without this the fixtures are unreachable: nothing in a browser spawns a run,
 * so nothing ever calls `monitor`, and the pane goes on saying *Nothing is
 * running here yet.* over a set of readouts it was handed. With Rust behind it
 * this answers `null` and the pane stays where every other surface put it — a
 * readout's own `monitored` flag is the harness's account of what it is
 * streaming, and letting it drive this window's selection would make arriving
 * at a run something the app did rather than something an operator pressed.
 */
export function fixtureRunToOpenOn(readouts: readonly RunReadout[]): number | null {
  if (hasRustBehindIt()) return null;
  return (readouts.find((readout) => readout.monitored) ?? readouts[0])?.run ?? null;
}
