import { nowSeconds } from "../chrome/age";
import { hasRustBehindIt } from "../snapshot/snapshot";
import type { RunReadout } from "./runs";

/**
 * What `dev:web` boots a rack of runs from: hand-written readouts, checked in,
 * with no PTY and no Rust process anywhere behind them.
 *
 * They exist because the states worth looking at are the ones a browser cannot
 * be talked into. Spec #28 names it exactly — *you cannot conjure a wedged AFK
 * run to check its still-state* — and neither can a Tauri window on demand: a
 * wedged reading wants five minutes of a research run saying nothing, and an
 * `awaitingOperator` one wants a CLI that stopped on a trust prompt, which is a
 * machine state rather than a click.
 *
 * **They are not the snapshot fixtures, and the difference is their whole
 * weakness.** `src/snapshot/fixtures.ts` holds files *generated by the model
 * crate*, and the Rust build fails if a checked-in one has stopped matching —
 * so a snapshot fixture is the model's own output or it is nothing. A run
 * readout is not part of `Snapshot`, no generator emits one, and the only thing
 * standing between this file and fiction is the `RunReadout` annotation below
 * plus the two tests that pin the wire shape from either side. Adding a key in
 * Rust will not fail this file; renaming one will fail `tsc`, and that is the
 * line being relied on.
 *
 * Nothing here ever presents itself as a live read. The seeding below is on the
 * no-Rust branch only, for the same reason no snapshot fixture is stamped
 * `github`: a browser quietly showing fiction as an observation is the one
 * failure the provenance rules exist to prevent.
 */

/**
 * Everything a readout carries that these fixtures are not making a point
 * about. Typed as `RunReadout` so a key added on the Rust side and mirrored
 * into the interface fails the build here rather than being silently absent
 * from every fixture.
 */
const ORDINARY: FixtureRun = {
  run: 0,
  held: 0,
  dropped: 0,
  through: 0,
  end: 0,
  truncated: false,
  desynced: false,
  over: false,
  code: null,
  monitored: false,
  ending: "live",
  ticket: null,
  folder: null,
  kind: "work",
  silence: { kind: "nothing" },
  signal: null,
  kind: null,
  openedSecondsAgo: 0,
  quietSecondsAgo: 0,
};

/**
 * A fixture row, in durations rather than stamps.
 *
 * **Seconds-ago and never an absolute second**, which is the difference between
 * a fixture that keeps its meaning and one that rots: the whole point of a row
 * is *silent for six minutes*, and a stamp checked in on the day this file was
 * written would read as silent for a year. `runFixtureNamed` turns them into
 * the stamps a readout carries, against the clock the window is running on now.
 */
export interface FixtureRun extends Omit<RunReadout, "opened" | "spoke"> {
  openedSecondsAgo: number;
  quietSecondsAgo: number;
}

function a(readout: Partial<FixtureRun> & Pick<FixtureRun, "run">): FixtureRun {
  return { ...ORDINARY, ...readout };
}

/** One fixture row as Rust would have sent it: durations resolved to stamps. */
function stamped({ openedSecondsAgo, quietSecondsAgo, ...readout }: FixtureRun): RunReadout {
  const now = nowSeconds();
  return { ...readout, opened: now - openedSecondsAgo, spoke: now - quietSecondsAgo };
}

/** An hour of a person reading a diff, which is the most ordinary thing there is. */
const QUIET_HOUR = a({
  run: 1,
  kind: "work",
  openedSecondsAgo: 10_800,
  quietSecondsAgo: 62 * 60,
  ticket: 50,
  folder: "/work/perseverance",
  held: 262_144,
  through: 262_144,
  end: 262_144,
  monitored: true,
  silence: { kind: "quiet", silentForMs: 62 * 60_000 },
  signal: "busy",
});

/** A CLI that never opened its session, because its own trust prompt is up. */
const AWAITING_OPERATOR = a({
  run: 2,
  kind: "work",
  openedSecondsAgo: 150,
  quietSecondsAgo: 12,
  ticket: 51,
  folder: "/work/perseverance",
  monitored: true,
  silence: { kind: "wedged", why: "awaitingOperator", unopenedForMs: 12_000 },
});

/**
 * The one this file exists for: an unattended run, silent past the fallback,
 * with nobody in front of it and no signal ever observed.
 */
const UNWATCHED = a({
  run: 3,
  kind: "research",
  openedSecondsAgo: 2_520,
  quietSecondsAgo: 5 * 60 + 4,
  ticket: 52,
  folder: "/work/perseverance",
  held: 8_192,
  through: 8_192,
  end: 8_192,
  monitored: true,
  kind: "research",
  silence: { kind: "wedged", why: "silent", silentForMs: 5 * 60_000 + 4_000 },
});

/** A closed ticket over a child that may still be printing. Never quiet, ever. */
const SPENT = a({
  run: 4,
  kind: "work",
  openedSecondsAgo: 18_000,
  quietSecondsAgo: 3,
  ticket: 47,
  folder: "/work/perseverance",
  held: 131_072,
  through: 131_072,
  end: 131_072,
  monitored: true,
  ending: "spent",
  silence: { kind: "spent" },
  signal: "ready",
});

/** A child that stopped, where the ending is the reading and the silence is not. */
const ENDED = a({
  run: 5,
  kind: "research",
  openedSecondsAgo: 740,
  quietSecondsAgo: 740,
  ticket: 44,
  folder: "/work/perseverance",
  held: 65_536,
  through: 65_536,
  end: 65_536,
  over: true,
  code: 130,
  monitored: true,
  ending: "exited",
});

/**
 * The ordinary case, and the only one here that is not a state a browser
 * struggles to reach: a run printing right now.
 *
 * It earns a fixture anyway, because it is what the other five are read
 * against. Its silence is `nothing` — Rust's floor, not an absence of data —
 * and the pane says nothing about it beside a terminal that is visibly working.
 * Without it on screen the readings look like a set of complaints with no
 * baseline, and `quiet · 0s` on a healthy run would have been invisible to
 * every fixture in this file.
 */
const STREAMING = a({
  run: 7,
  kind: "work",
  openedSecondsAgo: 1_560,
  quietSecondsAgo: 0,
  ticket: 54,
  folder: "/work/perseverance",
  held: 49_152,
  through: 49_152,
  end: 49_152,
  silence: { kind: "nothing" },
  signal: "busy",
});

/** A run a watch has seen go idle, so the third signal is a thing on screen too. */
const IDLING = a({
  run: 6,
  kind: "compose",
  openedSecondsAgo: 900,
  quietSecondsAgo: 90,
  ticket: 53,
  folder: "/work/other",
  held: 4_096,
  through: 4_096,
  end: 4_096,
  silence: { kind: "quiet", silentForMs: 90_000 },
  signal: "idle",
});

/**
 * A run this app was never told the stakes of: no ticket, no folder, no kind.
 *
 * On the rack for the reason the others are — it is a row that has to draw, and
 * a row that guessed *work* would be naming something nobody said.
 */
const UNSTAKED = a({
  run: 8,
  held: 12_288,
  through: 4_096,
  end: 12_288,
  openedSecondsAgo: 420,
  quietSecondsAgo: 20,
});

/**
 * The six rows the rack itself is read against.
 *
 * A set of its own rather than a reading of `the-rack` above, because the two
 * are about different things: that one is every *silence* at once, and this one
 * is every *row* at once — all four kinds, a run nobody staked, a terminal a
 * megabyte behind, and one that has landed. Six of them, because *the tier is
 * width and never N* is a claim, and a fixture with two rows in it would let
 * that claim rot without anything going red.
 */
const RACK: FixtureRun[] = [
  a({
    run: 1,
    kind: "work",
    ticket: 214,
    folder: "C:\\Users\\you\\Workspace\\perseverance",
    openedSecondsAgo: 10_800,
    quietSecondsAgo: 3,
    held: 482_112,
    through: 480_000,
    end: 482_112,
  }),
  a({
    run: 2,
    kind: "research",
    ticket: 217,
    folder: "C:\\Users\\you\\Workspace\\perseverance",
    openedSecondsAgo: 2_520,
    quietSecondsAgo: 372,
    held: 90_210,
    through: 90_210,
    end: 90_210,
  }),
  a({
    run: 3,
    kind: "chart",
    folder: "D:\\Archive\\atlas",
    openedSecondsAgo: 740,
    quietSecondsAgo: 18,
    held: 4_194_304,
    dropped: 65_536,
    through: 2_989_424,
    end: 4_194_304,
    truncated: true,
    desynced: true,
  }),
  a({
    run: 4,
    kind: "work",
    ticket: 219,
    folder: "C:\\Users\\you\\Workspace\\perseverance",
    openedSecondsAgo: 18_000,
    quietSecondsAgo: 5_760,
    held: 128_744,
    through: 128_744,
    end: 128_744,
    over: true,
    code: 0,
    ending: "spent",
    silence: { kind: "spent" },
  }),
  a({
    run: 5,
    openedSecondsAgo: 150,
    quietSecondsAgo: 92,
    held: 640,
    through: 0,
    end: 640,
  }),
  a({
    run: 6,
    kind: "compose",
    folder: "C:\\Users\\you\\Workspace\\ledger",
    openedSecondsAgo: 1_560,
    quietSecondsAgo: 205,
    held: 20_480,
    through: 20_352,
    end: 20_480,
  }),
];

/**
 * The sets, each named for the reading it is there to put on screen.
 *
 * `none` is the default and is empty, so that a `dev:web` tab opened without
 * asking for runs is the tab this app has always opened: nothing bound, and
 * *Nothing is running here yet.* still a state somebody can look at.
 *
 * `the-rack` is every reading at once and every signal at once, which is the
 * only place the silences can be compared rather than remembered — the working
 * run among them, because a set of readings with no baseline reads as a set of
 * complaints.
 */
export const RUN_FIXTURES = {
  none: [],
  streaming: [STREAMING],
  quiet: [QUIET_HOUR],
  "awaiting-operator": [AWAITING_OPERATOR],
  unwatched: [UNWATCHED],
  spent: [SPENT],
  ended: [ENDED],
  "the-rack": [
    a({ ...AWAITING_OPERATOR, monitored: true }),
    a({ ...QUIET_HOUR, monitored: false }),
    a({ ...UNWATCHED, monitored: false }),
    a({ ...SPENT, monitored: false }),
    a({ ...ENDED, monitored: false }),
    STREAMING,
    IDLING,
    UNSTAKED,
  ],
  rack: RACK,
} satisfies Record<string, FixtureRun[]>;

export type RunFixtureName = keyof typeof RUN_FIXTURES;

export const RUN_FIXTURE_NAMES = Object.keys(RUN_FIXTURES) as RunFixtureName[];

export const DEFAULT_RUN_FIXTURE: RunFixtureName = "none";

/** A copy each time, so a caller editing one cannot edit the fixture itself. */
export function runFixtureNamed(name: RunFixtureName): RunReadout[] {
  return (structuredClone(RUN_FIXTURES[name]) as FixtureRun[]).map(stamped);
}

/**
 * Which set of runs a `dev:web` URL asked for.
 *
 * `?runs=` beside `?map=` and `?env=`, spelled once here: the parameter names
 * the thing being stood in for and the value names the state. An unknown name
 * falls back to the default rather than throwing, for the same reason a typo in
 * `?map=` does not blank the window.
 */
export const RUNS_PARAMETER = "runs";

export function requestedRunFixture(search?: string): RunFixtureName {
  const from = search ?? (typeof window === "undefined" ? "" : window.location.search);
  const asked = new URLSearchParams(from).get(RUNS_PARAMETER);
  return isRunFixtureName(asked) ? asked : DEFAULT_RUN_FIXTURE;
}

export function isRunFixtureName(name: string | null): name is RunFixtureName {
  return name !== null && name in RUN_FIXTURES;
}

/**
 * Which of a fixture set's runs the pane opens on, and `null` whenever there is
 * a harness behind the window.
 *
 * Without this the fixtures are unreachable: nothing in a browser spawns a run,
 * so nothing ever calls `monitor`, and the pane goes on saying *Nothing is
 * running here yet.* over a set of readouts it was handed. With Rust behind it
 * this answers `null` and the pane stays where every other surface put it — a
 * readout's own `monitored` flag is the harness's account of what it is
 * streaming, and letting it drive this window's selection would make arriving
 * at a run something the app did rather than something an operator pressed.
 */
export function fixtureRunToOpenOn(readouts: readonly RunReadout[]): number | null {
  if (hasRustBehindIt()) return null;
  return (readouts.find((readout) => readout.monitored) ?? readouts[0])?.run ?? null;
}
