/**
 * The rendered matrix: an instrument, and emphatically not a gate.
 *
 * It answers *where does this contract actually stand* in one page — which
 * rules are held by a construction, which by a test, which by a person, and
 * what every view has written under the ones a person keeps. Nothing conforms
 * because a cell here says so, and the only thing any test is allowed to assert
 * about the output is that it is current with the registry and the
 * declarations. A matrix that gated would make the artifact the contract, and
 * then a rule would be kept by whoever last regenerated a file.
 *
 * **Rows are rules.** Not rule × state, not rule × view × state: the unit of
 * conformance is the rule, and the fixture space is a fan-out inside one
 * assertion rather than a set of cells anybody maintains by hand.
 */

import type { Rule } from "../../src/contract/rules";
import { deviationFor } from "../../src/contract/rules";
import type { ViewDeclaration } from "./contract";
import { sectionFor } from "./contract";

/** What holds the rule today, short enough for a table cell. */
export function enforcedBy(rule: Rule): string {
  switch (rule.tier) {
    case "structural":
      return `construction in \`${rule.mechanismPath}\``;
    case "asserted":
      return rule.renderBound
        ? "assertion over the fixture space (#43)"
        : "enumeration over the stylesheets (#43)";
    case "judged":
      return rule.assertedFloor === undefined
        ? "declaration only — no floor a machine can settle"
        : "asserted floor (#43), then declaration";
  }
}

export type DeclarationStatus =
  | "no slot"
  | "no declaration file"
  | "undeclared"
  | "declared"
  | "declared, with deviation";

export function declarationStatus(
  rule: Rule,
  declaration: ViewDeclaration,
): DeclarationStatus {
  if (!deviationFor(rule).declarable) return "no slot";
  if (declaration.parsed === null) return "no declaration file";
  const section = sectionFor(declaration, rule.id);
  if (section === undefined || section.statement.length === 0) return "undeclared";
  return section.deviations.length > 0 ? "declared, with deviation" : "declared";
}

export interface WorklistItem {
  readonly view: string;
  readonly rule: Rule;
  /** The declared paragraph, as written. The worklist quotes; it never edits. */
  readonly text: string;
}

export function worklist(
  rules: readonly Rule[],
  declarations: readonly ViewDeclaration[],
): WorklistItem[] {
  const items: WorklistItem[] = [];
  for (const declaration of declarations) {
    for (const rule of rules) {
      if (!deviationFor(rule).declarable) continue;
      for (const text of sectionFor(declaration, rule.id)?.deviations ?? []) {
        items.push({ view: declaration.view, rule, text });
      }
    }
  }
  return items;
}

function row(cells: readonly string[]): string {
  return `| ${cells.join(" | ")} |`;
}

export function renderMatrix(
  rules: readonly Rule[],
  declarations: readonly ViewDeclaration[],
): string {
  const views = declarations.map((declaration) => declaration.view);
  const lines: string[] = [
    "# The encoding contract, as it stands",
    "",
    "<!-- Generated by `npm run contract:matrix`. Edit the registry or a",
    "     declaration, not this file. -->",
    "",
    "Thirteen rules, one tier each, and one row per rule — never a row per",
    "rendered state. The tier says what keeps the rule and therefore what a",
    "violation looks like: *structural* means it cannot be written down,",
    "*asserted* means a test decides and a red test is the failure with no",
    "appeal, *judged* means part of the obligation is about what a person reads,",
    "so a person decides in writing.",
    "",
    "**This page gates nothing.** It is an instrument. The only thing any test",
    "asserts about it is that it is current; conformance is settled by the",
    "constructions, the assertions and the declarations it points at.",
    "",
    "The registry is [`src/contract/rules.ts`](../../src/contract/rules.ts); the",
    "classification is",
    "[ADR 0020](../adr/0020-the-contract-is-thirteen-rules-in-three-tiers.md).",
    "",
    "## The thirteen",
    "",
    row(["#", "Rule", "Subject", "Tier", "Render-bound", "Where it is enforced", ...views]),
    row([
      "---",
      "---",
      "---",
      "---",
      "---",
      "---",
      ...views.map(() => "---"),
    ]),
  ];

  for (const rule of rules) {
    lines.push(
      row([
        String(rule.id),
        rule.name,
        rule.subject,
        rule.tier === "judged" ? "**judged**" : rule.tier,
        rule.renderBound ? "yes" : "no",
        enforcedBy(rule),
        ...declarations.map((declaration) => declarationStatus(rule, declaration)),
      ]),
    );
  }

  lines.push(
    "",
    "A view column reads `no slot` wherever the rule is structural or asserted.",
    "That is not an omission: deviation is a function of tier, and only a judged",
    "rule has a route for one. An asserted rule that fails has a red test and no",
    "appeal; a structural rule has nothing to declare because there is nothing to",
    "declare it about.",
    "",
    "## The deviation worklist",
    "",
    "A declared deviation is fog on the contract, not a carve-out. Each item",
    "below is work scheduled to be worked off — the declaration says what the",
    "view does today, and this list is what the contract is owed. Quoted from the",
    "declarations verbatim.",
    "",
  );

  const items = worklist(rules, declarations);
  if (items.length === 0) {
    lines.push("Nothing is declared as a deviation today.", "");
  } else {
    for (const item of items) {
      lines.push(
        `### ${item.view} — rule ${item.rule.id}, ${item.rule.name}`,
        "",
        item.text,
        "",
      );
    }
  }

  lines.push(
    "## Open obligations that are not deviations",
    "",
    "An asserted rule has no deviation route, so a fact about the tree that its",
    "assertion has yet to settle is registered on the rule instead. It appears",
    "here because leaving it off this page would make the page read as complete.",
    "",
  );
  lines.push(...entries(rules, (rule) => rule.tension, "Nothing is open today."));

  lines.push(
    "## Settled, where an obligation was open",
    "",
    "The same facts, once the assertion that had to settle them was written.",
    "They stay on the page rather than dissolving into a commit message: a",
    "reader asking why a check is drawn where it is should find the answer here",
    "rather than reconstruct it. An entry sits under exactly one of these two",
    "headings, so *settled* is never read off silence in the section above.",
    "",
  );
  lines.push(...entries(rules, (rule) => rule.settlement, "Nothing has been settled this way yet."));

  return `${lines.join("\n").trimEnd()}\n`;
}

/**
 * One section per rule that has the field, or one honest sentence saying none
 * does. A heading with nothing under it would read as a rendering bug rather
 * than as the answer, which is the one thing an instrument may not do.
 */
function entries(
  rules: readonly Rule[],
  field: (rule: Rule) => string | undefined,
  empty: string,
): string[] {
  const lines: string[] = [];
  for (const rule of rules) {
    const text = field(rule);
    if (text === undefined) continue;
    lines.push(`### Rule ${rule.id}, ${rule.name} (${rule.tier})`, "", text, "");
  }
  return lines.length === 0 ? [empty, ""] : lines;
}
